package auction_fest;


/**
* auction_fest/auction_clientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public interface auction_clientOperations 
{
  boolean offer (String seller_name, String item_name, float starting_price) throws auction_fest.auction_clientPackage.OfferItemException;
  boolean sell (String item_name) throws auction_fest.auction_clientPackage.SellItemException;
  boolean bid (String user_name, float bid_price) throws auction_fest.auction_clientPackage.BidItemException;
  String view_high_bidder (String itemName) throws auction_fest.auction_clientPackage.SellItemException;
  String view_bid_status (String userId) throws auction_fest.auction_clientPackage.BidItemException;
  String view_auction_status () throws auction_fest.auction_clientPackage.StatusException;
} // interface auction_clientOperations
