package auction_fest;


/**
* auction_fest/auction_clientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

abstract public class auction_clientHelper
{
  private static String  _id = "IDL:auction_fest/auction_client:1.0";

  public static void insert (org.omg.CORBA.Any a, auction_fest.auction_client that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static auction_fest.auction_client extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (auction_fest.auction_clientHelper.id (), "auction_client");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static auction_fest.auction_client read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_auction_clientStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, auction_fest.auction_client value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static auction_fest.auction_client narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof auction_fest.auction_client)
      return (auction_fest.auction_client)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      auction_fest._auction_clientStub stub = new auction_fest._auction_clientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static auction_fest.auction_client unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof auction_fest.auction_client)
      return (auction_fest.auction_client)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      auction_fest._auction_clientStub stub = new auction_fest._auction_clientStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
