package auction_fest;


/**
* auction_fest/auction_clientPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public abstract class auction_clientPOA extends org.omg.PortableServer.Servant
 implements auction_fest.auction_clientOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("offer", new java.lang.Integer (0));
    _methods.put ("sell", new java.lang.Integer (1));
    _methods.put ("bid", new java.lang.Integer (2));
    _methods.put ("view_high_bidder", new java.lang.Integer (3));
    _methods.put ("view_bid_status", new java.lang.Integer (4));
    _methods.put ("view_auction_status", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // auction_fest/auction_client/offer
       {
         try {
           String seller_name = in.read_string ();
           String item_name = in.read_string ();
           float starting_price = in.read_float ();
           boolean $result = false;
           $result = this.offer (seller_name, item_name, starting_price);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (auction_fest.auction_clientPackage.OfferItemException $ex) {
           out = $rh.createExceptionReply ();
           auction_fest.auction_clientPackage.OfferItemExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // auction_fest/auction_client/sell
       {
         try {
           String item_name = in.read_string ();
           boolean $result = false;
           $result = this.sell (item_name);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (auction_fest.auction_clientPackage.SellItemException $ex) {
           out = $rh.createExceptionReply ();
           auction_fest.auction_clientPackage.SellItemExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // auction_fest/auction_client/bid
       {
         try {
           String user_name = in.read_string ();
           float bid_price = in.read_float ();
           boolean $result = false;
           $result = this.bid (user_name, bid_price);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (auction_fest.auction_clientPackage.BidItemException $ex) {
           out = $rh.createExceptionReply ();
           auction_fest.auction_clientPackage.BidItemExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // auction_fest/auction_client/view_high_bidder
       {
         try {
           String itemName = in.read_string ();
           String $result = null;
           $result = this.view_high_bidder (itemName);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (auction_fest.auction_clientPackage.SellItemException $ex) {
           out = $rh.createExceptionReply ();
           auction_fest.auction_clientPackage.SellItemExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // auction_fest/auction_client/view_bid_status
       {
         try {
           String userId = in.read_string ();
           String $result = null;
           $result = this.view_bid_status (userId);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (auction_fest.auction_clientPackage.BidItemException $ex) {
           out = $rh.createExceptionReply ();
           auction_fest.auction_clientPackage.BidItemExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // auction_fest/auction_client/view_auction_status
       {
         try {
           String $result = null;
           $result = this.view_auction_status ();
           out = $rh.createReply();
           out.write_string ($result);
         } catch (auction_fest.auction_clientPackage.StatusException $ex) {
           out = $rh.createExceptionReply ();
           auction_fest.auction_clientPackage.StatusExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:auction_fest/auction_client:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public auction_client _this() 
  {
    return auction_clientHelper.narrow(
    super._this_object());
  }

  public auction_client _this(org.omg.CORBA.ORB orb) 
  {
    return auction_clientHelper.narrow(
    super._this_object(orb));
  }


} // class auction_clientPOA
