package auction_fest;

/**
* auction_fest/auction_clientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class auction_clientHolder implements org.omg.CORBA.portable.Streamable
{
  public auction_fest.auction_client value = null;

  public auction_clientHolder ()
  {
  }

  public auction_clientHolder (auction_fest.auction_client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = auction_fest.auction_clientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    auction_fest.auction_clientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return auction_fest.auction_clientHelper.type ();
  }

}
