package auction_fest.auction_clientPackage;


/**
* auction_fest/auction_clientPackage/auction_status.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class auction_status implements org.omg.CORBA.portable.IDLEntity
{
  public String user = null;
  public String item = null;
  public float currentPrice = (float)0;

  public auction_status ()
  {
  } // ctor

  public auction_status (String _user, String _item, float _currentPrice)
  {
    user = _user;
    item = _item;
    currentPrice = _currentPrice;
  } // ctor

} // class auction_status
