package auction_fest.auction_clientPackage;

/**
* auction_fest/auction_clientPackage/auction_statusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class auction_statusHolder implements org.omg.CORBA.portable.Streamable
{
  public auction_fest.auction_clientPackage.auction_status value = null;

  public auction_statusHolder ()
  {
  }

  public auction_statusHolder (auction_fest.auction_clientPackage.auction_status initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = auction_fest.auction_clientPackage.auction_statusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    auction_fest.auction_clientPackage.auction_statusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return auction_fest.auction_clientPackage.auction_statusHelper.type ();
  }

}
