package auction_fest.auction_clientPackage;


/**
* auction_fest/auction_clientPackage/OfferItemException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class OfferItemException extends org.omg.CORBA.UserException
{
  public String description = null;

  public OfferItemException ()
  {
    super(OfferItemExceptionHelper.id());
  } // ctor

  public OfferItemException (String _description)
  {
    super(OfferItemExceptionHelper.id());
    description = _description;
  } // ctor


  public OfferItemException (String $reason, String _description)
  {
    super(OfferItemExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class OfferItemException
