package auction_fest.auction_clientPackage;


/**
* auction_fest/auction_clientPackage/SellItemException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class SellItemException extends org.omg.CORBA.UserException
{
  public String description = null;

  public SellItemException ()
  {
    super(SellItemExceptionHelper.id());
  } // ctor

  public SellItemException (String _description)
  {
    super(SellItemExceptionHelper.id());
    description = _description;
  } // ctor


  public SellItemException (String $reason, String _description)
  {
    super(SellItemExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class SellItemException
