package auction_fest.auction_clientPackage;


/**
* auction_fest/auction_clientPackage/StatusException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class StatusException extends org.omg.CORBA.UserException
{
  public String description = null;

  public StatusException ()
  {
    super(StatusExceptionHelper.id());
  } // ctor

  public StatusException (String _description)
  {
    super(StatusExceptionHelper.id());
    description = _description;
  } // ctor


  public StatusException (String $reason, String _description)
  {
    super(StatusExceptionHelper.id() + "  " + $reason);
    description = _description;
  } // ctor

} // class StatusException
