package auction_fest.auction_clientPackage;


/**
* auction_fest/auction_clientPackage/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

abstract public class StatusHelper
{
  private static String  _id = "IDL:auction_fest/auction_client/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, auction_fest.auction_clientPackage.auction_status that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static auction_fest.auction_clientPackage.auction_status extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = auction_fest.auction_clientPackage.auction_statusHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (auction_fest.auction_clientPackage.StatusHelper.id (), "Status", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static auction_fest.auction_clientPackage.auction_status read (org.omg.CORBA.portable.InputStream istream)
  {
    auction_fest.auction_clientPackage.auction_status value = null;
    value = auction_fest.auction_clientPackage.auction_statusHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, auction_fest.auction_clientPackage.auction_status value)
  {
    auction_fest.auction_clientPackage.auction_statusHelper.write (ostream, value);
  }

}
