package auction_fest.auction_clientPackage;

/**
* auction_fest/auction_clientPackage/StatusExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AuctionFest.idl
* Saturday, March 11, 2017 11:26:53 AM PST
*/

public final class StatusExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public auction_fest.auction_clientPackage.StatusException value = null;

  public StatusExceptionHolder ()
  {
  }

  public StatusExceptionHolder (auction_fest.auction_clientPackage.StatusException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = auction_fest.auction_clientPackage.StatusExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    auction_fest.auction_clientPackage.StatusExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return auction_fest.auction_clientPackage.StatusExceptionHelper.type ();
  }

}
